apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-agent-ccdt
data:
  ccdt.json: |
    {
      "channel": [
        {
          "name": "AGENT.SVRCONN",
          "clientConnection": {
            "connection": [
              {
                "host": "singleinstance-qm-ibm-mq.cp4i.svc.cluster.local",
                "port": 1414
              }
            ],
            "queueManager": "SINGLEINSTANCEQM"
          },
          "transmissionSecurity": {
            "cipherSpecification": "ANY_TLS12_OR_HIGHER"
          },
          "type": "clientConnection"
        }
      ]
    }
